name: releases

on:
  push:
    tags:
      - v*

jobs:
  build-apple:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable

      - name: Install tools
        run: |
          cargo install cbindgen
          brew install llvm unzip protobuf

      - name: Build macOS and iOS
        run: ./scripts/build_apple_xcframework.sh

      - name: Zip XCFramework
        run: |
          mv target/apple/release/leaf.xcframework .
          zip -r leaf.xcframework.zip leaf.xcframework

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaf.xcframework.zip
          path: leaf.xcframework.zip
